### ISSUE TITLE
Error with jaxlib

### ISSUE THREAD

**Issue by TuongViDang** [DendrouLab/panpipes-tutorials#10]
Hello,
I run the command: panpipes ingest config and dot this error:
RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. You may be able work around this issue by building jaxlib from source.
Thank you,

**Comment by TuongViDang** [comment]
"conda install jax" solves the problem :)
Thank you

**Comment by bio-la** [comment]
thanks for using panpipes!
