### ISSUE TITLE
issue on multimodal integration tutorial 

### ISSUE THREAD

**Issue by giuliaelgarcia** [DendrouLab/panpipes-tutorials#25]
Pipeline.yml from the tutorial has an option in the total VI `filter_adt_outliers` however that does not allow it to run properly. The tutorial git yml [(pipeline_integration.yml)](https://github.com/DendrouLab/panpipes-tutorials/blob/main/docs/uni_multi_integration/pipeline.yml#L227) shows an outdated version, however the panpipes git yml has an updated version [which](https://github.com/DendrouLab/panpipes/blob/main/panpipes/panpipes/pipeline_integration/pipeline.yml#L230) fixes the issue by replacing it with `filter_prot_outliers`. So tutorial yml should be updated as well

**Comment by bio-la** [comment]
this is sorted in https://github.com/DendrouLab/panpipes-tutorials/commit/526ffc65001ef89ec5ff7b3d155abe1b8d0fea0c
