### ISSUE TITLE
Visualisation Issue 4 

### ISSUE THREAD

**Issue by giuliaelgarcia** [DendrouLab/panpipes-tutorials#31]
Scatter color function is not working and it can't recognize any inputs (even a hex colour code). 
Tried changing the[ pair_scatters_markers.csv](https://panpipes-tutorials.readthedocs.io/en/latest/_downloads/68a767929ecdc47cf945f855f58e046a/paired_scatters_markers.csv) colour indication to `rna:douplet_scores`, d`ouplet_scores` and a `hex code` and all of them errored 
The first two features are read fine but not the third one. 
Tested in python environment with `mu.pl.scatter` function and same error appeared. 
Also tested following error [suggestion](https://github.com/scverse/muon/issues/48)  of doubling the `rna:rna:doublet_scores` and same issue appeared again. 
Additionally tested with the `sc.pl.scatter` function in a python environment using simple gene markers and color as `doublet_scores`and it worked so it must be a muon issue. 
Additionally no instruction on how to accurately create the input file for scatter plots on the visualisation [workflow](https://panpipes-pipelines.readthedocs.io/en/latest/workflows/vis.html) or the gene format [list](https://panpipes-pipelines.readthedocs.io/en/latest/usage/gene_list_format.html).

**Comment by SarahOuologuem** [comment]
Hi! yes, you're right, it's a Muon issue. 

When i run `sc.pl.scatter()` it throws an error when specifying the color as a list, e.g. `color=["total_counts"]`. Are you also getting this error? 
Therefore, for me, the errors were solved when i deleted the line `color = [color]` in [line 75 in plot.py](https://github.com/scverse/muon/blob/master/muon/_core/plot.py#L75)

I then ran the vis workflow of panpipes with the changed source code and the following [paired_scatters_markers.csv](https://github.com/DendrouLab/panpipes-tutorials/files/14296314/paired_scatters_markers.csv) and [paired_scatters.csv](https://github.com/DendrouLab/panpipes-tutorials/files/14296315/paired_scatters.csv) 
(on the [test data provided in the tutorial ](https://figshare.com/articles/dataset/Data_to_run_visualization_tutorial_https_panpipes-tutorials_readthedocs_io_en_latest_visualization_vis_with_panpipes_html_/24612087) with the [provided yaml of the tutorial](https://panpipes-tutorials.readthedocs.io/en/latest/_downloads/29daa86241829b362152785caf30ab61/pipeline.yml))

I then get the following three plots
<img src="https://github.com/DendrouLab/panpipes-tutorials/assets/68101181/119cd061-cd34-4fab-b7f0-d4d2dc72c4b9" width=30% height=30%> <img src="https://github.com/DendrouLab/panpipes-tutorials/assets/68101181/2ba5d501-565e-4492-aad2-c2e17ef16eea" width=30% height=30%> <img src="https://github.com/DendrouLab/panpipes-tutorials/assets/68101181/2d4664cf-0dc6-4ceb-a8fc-7b2d18651986" width=30% height=30%>

@giuliaelgarcia, please let me know whether it also works for you when changing the source code of muon in plot.py. Or are you getting any different errors? Thanks!
